branches:
    only:
        - master
  
skip_tags: false

skip_non_tags: false

skip_commits:
    files:
        - '**\AssemblyInfo.*'
        - 'CHANGELOG.md'
        - 'README.md'

pull_requests:
    do_not_increment_build_number: true
  
image: Visual Studio 2017

assembly_info:
    patch: false

configuration: Release

platform: Any CPU
  
environment:
    CHANGELOG_GITHUB_TOKEN:
        secure: yNRb78M1kncUfbzKLWl1igKg2piIARVYUpr0508PrTS7N/AwwnYozd+Ntr1gfUT+
    auth_token:
        secure: yNRb78M1kncUfbzKLWl1igKg2piIARVYUpr0508PrTS7N/AwwnYozd+Ntr1gfUT+
    github_user:
        secure: EHfj3CL5trOMzKP1sceM5A== 
    github_email:
        secure: G641hL9+GJDfG5+L1lw0guzFoZlPVu1Zp+P39/l7/rU=
    priv_key:
        secure: 6EZ/isMS0OeU/OFTHH0qO9hXFWHStbiTkuHhspdGZb4gZ8gdDFIqWk7wWG77rVIvDQObjv75tDCpdq9bJH5DhJkF+jttHBxZS+rqcDdwMwXWqyrVatCyiB/shYa3N860H2myt+dr+t+WVRbUWEu3x5SGSD6YgRz5w2T47Dblfnx1O8/OgQFSYY8L1df/44XXU4u/DybIFYcfXbGkfNI2d5o8rCixvY+60r4djo31bmYYU9Nulz1NnjcmdqSrKP3kVkCjrKYpD+9vwImhTu+xxN2V9M+kFY+n5Zl/BDF3QyCduaux9d1Ow0wwntunZ8cyulHbF3NX63KvSFyG8ffuY8FIDas4nHOL1L+UaSpPjhRi3aLeO9pLhASQBcMEpokXokcm8un/pw2JE08jNtXv3QLlmJwO1Ep7bc7eSxBJ/1enCnzIcDnuPxcqYJf0GPNbOI5Z7QVqxSbP0h2JA4p1ggA+viIrOwZI5XGKFpHq45GE7tmV+rSFut4D3zdaDb3UIiHYk2hPyRPnZTcwcqxZXrIf3FN9qKXwJBSDKns/9oWVfmiQOQdV4Qs5AR6H9ojmRu2xkynfyJGEwlkQ6CRCK7wNoG7NJe6tsezqCsiHEdbRg2AET+smc20fcKBhE+dXSb5UTjLTx51to+iNyENx00h4vTyIDu+Vj3Zrhgkfjtd88yUS9/sWaqlD1kMorMqHHZKKQ3iv1zWZiBUWXf9JuvpoTan3e8+ACJ6XWboIpUUE8Rsn7udauOzNngOeaS5H/ta7rQCaO2pMImEFPIEvvOGh81eoAhxMOk+skKTNDJHgjhrEPhGr+Df6gWGWVNDTFDs7eqRi/3Jz1ktd6dxaQ0RpbvrOo63mMTtGC0LD3GzHpRm9MBtoXBpo1iEcdRVzWF/7lmPlaE/ctErL9OuLOZQiD8p9D4Sy5z8FmMyCZF/WYsD98jID92TbJvLr6kVfBXCG4b4aDt7lPbMuoiCLJ7jcy9/DfW8Y559T3J9tkN8d/e4giCgFJxVq/81gFfNxgGz44VUvPRF957e6uncN1yYYS8jI9JmfHNPYp5iaksuDOVQlE0MBNVUGOdK9YLM1BI64JVeRLDRCOto9hzmqSyyv+FV20dkPCqEkJOYj2R+D6YVGb39WXC3kDuXP1Bhots1KbF+HQW6iQgD/iMukll6qytck/4o5fw4hqrxBgZ+2xnu2pQqQgWt3MM3rT1+b6KgHBZ3tDfBctXQzxW232Hn4+dD9m3MAbBbWmmo6jST+tbGq/QepeYnxCWDVpQVWukuCldkX2gm/BkdnAvHg80uoumJb0rwR48bMyZZrk54D5vR9I5VCJhSxkmcmjx+Cw1nVdbUwEJVeLgHoaY5+P8uVJk7mdCkfe4NnkoltM7YOFDKzDIj/nWeEV/Ionxvvis7Egz4DnZZUAEFHd0fjf2f9cD1XDgxoE/5IeMOoSooQCwpk9PfShkigAm2Xz0Y01wtijPWXuLIlxX+1akgjMK05G9wsxPyImDW+n9qfFzEfsJgP/c3OCSVzqJjyNu95570IBUHSEpqd8HLPeEkkZxBzHfoq2ansOo9vSSxcxUX9N4oZYupmxkvp6+FtdkZx++zuodrvOJJK3BlHfLlejz09bKd+kgxG44c4fsC1RO/i7sqn+7qIKIN9i559m+rSqwWuTevwy/811ieLEZ8HeFZlt7DsfpgUsC44PFuuRbm3eXoz8nEl9QmqLoKwk92IVCHf67EKQkW9mwjC8l5eI0NG5rUoAKDmWqK+KBWaE70T3SLw04iHknHdU7e8aqfHcu7r5AYqS8V5TRXrKMVTe+CiEmyIpJTAEEsVk6FCN0pYJNx/dK/eJBDptL3siIwn/dyv7J3Xsw5jU/ctxHjTHLqabep6/a5J7sEnJQwbuZGNChHFDCtvrYo8Is0ruqrdrzYhF5v6H2MMHKe7+qwSsObcSJttE+FI+1Gs9Bf5dkUp5vL/Hw5vnoLTicD8T03n0GoLUbuD6Ro/jPH4z0uMqKD5wS8JqfmEoqMrHKtepo7TyeUtM/igcoa4FTZHCtmZBFhX90jwcah38LCN7EYvJezf3I/ouBZoFKixScf1x+II+kdIfy+6UL3MFQJMPArAdhIY3LkPHJn8/qVlzbzLARxTsITpyXphTijDzCDtF55BRSoBJpMik0fShxUnb4Os6jLRB2U5JmFnFhn+HRkDgBudYfC5saP02k0Rk/g94USUSmMb99hu9ltePwvqs1Fkr13r5qXuwcKBImW+BTau4g2bUkaXv23g6eodQJxK5B8=

install:
    - git submodule update --init --recursive  

init:
    - ps: >-
        if ($env:APPVEYOR_REPO_TAG -eq "true")
        {
            $env:DracoLib_Version = "$($env:APPVEYOR_REPO_TAG_NAME.Replace('v', ''))";
        }
        else
        {
            $env:DracoLib_Version = "$($env:APPVEYOR_BUILD_VERSION)";
        }
        
build:
    verbosity: quiet

before_build:
    - nuget restore
  
build_script:

test: off
  
after_build:
    - ps: >-
        Remove-Item "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)" -Recurse -ErrorAction Ignore;
        New-Item -ItemType Directory -Force -Path "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)";
        New-Item -ItemType Directory -Force -Path "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)";
        if ($env:PLATFORM -eq "x86")
        {
            Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\DracoLib\bin\$($env:PLATFORM)\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\DracoLib" -Force;
        }  
        elseif ($env:PLATFORM -eq "x64")
        {
            Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\DracoLib\bin\$($env:PLATFORM)\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\DracoLib" -Force;
        }
        elseif ($env:PLATFORM -eq "Any CPU")
        {
            Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\DracoLib\bin\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\DracoLib" -Force;
        }
  
artifacts:

  - path: '\$(PLATFORM)\$(CONFIGURATION)\DracoLib'
    name: DracoLib
