namespace DracoProtos.Core.Enums
{
    public enum ArtifactType
	{
        ARTIFACT_REMOTE_BUILDING_CONTROL,
        ARTIFACT_ARENA_EXTRA_CREATURE,
        ARTIFACT_STOP_COOLDOWN,
        ARTIFACT_ARENA_EXTRA_START_LEVELS,
        ARTIFACT_TAXABLE_ARENAS,
        ARTIFACT_ARENA_FRIENDLY_EXTRA_EXP,
        ARTIFACT_ARENA_EXTRA_COLLECTION_TIME,
        ARTIFACT_RADAR_FILTER,
        ARTIFACT_BUDDY_BOOST,
        ARTIFACT_ROOST,
        ARTIFACT_EXPERIENCE,
        ARTIFACT_EXTRA_WEEKLY_QUEST,
        ARTIFACT_CHANGE_SPECIALIZATION,
        ARTIFACT_DECOY,
        ARTIFACT_OMIT_EASY_QUESTS,
        ARTIFACT_PINK_GLASSES,
        ARTIFACT_TAX_ALL_ARENAS,
        ARTIFACT_LIBRARY_CD_REDUCE,
        ARTIFACT_DUST_BONUS,
        ARTIFACT_BUFFS_FREEZE_DURING_SUPER_VISION,
        ARTIFACT_ARENA_TAX_FOR_ADDITIONAL_MONSTER,
        ARTIFACT_DURATION_EXTENDER
    }
}
